services:
  app:
    build: .
    container_name: la-parenthese
    env_file: .env
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.parenthese.rule=Host(`parenthese-reflexo.fr`) || Host(`www.parenthese-reflexo.fr`)"
      - "traefik.http.routers.parenthese.entrypoints=websecure"
      - "traefik.http.routers.parenthese.tls=true"
      - "traefik.http.routers.parenthese.tls.certresolver=resolverhttp"
      - "traefik.http.services.parenthese.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.parenthese-wwwredirect.redirectregex.regex=^https://www\\.parenthese-reflexo\\.fr/(.*)"
      - "traefik.http.middlewares.parenthese-wwwredirect.redirectregex.replacement=https://parenthese-reflexo.fr/$${1}"
      - "traefik.http.middlewares.parenthese-wwwredirect.redirectregex.permanent=true"
      - "traefik.http.routers.parenthese.middlewares=parenthese-wwwredirect"

networks:
  web:
    external: true
